In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [10]:
import string

In [19]:
from gensim import corpora
import gensim

In [22]:
from pprint import pprint

In [2]:
df=pd.read_csv("cleaned_tweets.csv")

In [3]:
df.head()

,Unnamed: 0,created_at,source,original_text,polarity,subjectivity,lang,favorite_count,retweet_count,original_author,followers_count,friends_count,possibly_sensitive,hashtags,user_mentions,place
0,0,2022-04-22 22:32:03+00:00,Twitter for iPhone,MICKEY’S BAD MOVE: @GovRonDeSantis has now sig...,-0.037500,0.533333,en,1,0.0,MercuryReports,9254,9422,False,[],['GovRonDeSantis'],All Over America
1,1,2022-04-22 22:16:55+00:00,Twitter for iPhone,ELECTIONS HAVE CONSEQUENCES: Biden’s historic ...,-0.066667,0.033333,en,1,0.0,MercuryReports,9254,9422,False,[],[],All Over America
2,2,2022-04-22 07:15:28+00:00,Twitter for iPhone,COINCIDENCE? 18 U.S. food processing facilitie...,-0.077778,0.177778,en,4,1.0,MercuryReports,9254,9422,False,[],[],All Over America
3,3,2022-04-22 07:11:18+00:00,Twitter for iPhone,FOOD PROCESSING PLANTS BEING DESTROYED: “A Sma...,-0.100000,0.450000,en,3,2.0,MercuryReports,9254,9422,False,[],[],All Over America
4,4,2022-04-21 22:22:02+00:00,Twitter for iPhone,DISGUSTING HUMAN BEING: What one person calls ...,-0.500000,0.550000,en,1,0.0,MercuryReports,9254,9422,False,[],[],All Over America

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4307 entries, 0 to 4306
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          4307 non-null   int64
 1   created_at          4307 non-null   object
 2   source              4307 non-null   object
 3   original_text       4307 non-null   object
 4   polarity            4307 non-null   float64
 5   subjectivity        4307 non-null   float64
 6   lang                4307 non-null   object
 7   favorite_count      4307 non-null   int64
 8   retweet_count       4307 non-null   float64
 9   original_author     4307 non-null   object
 10  followers_count     4307 non-null   int64
 11  friends_count       4307 non-null   int64
 12  possibly_sensitive  4307 non-null   bool
 13  hashtags            4307 non-null   object
 14  user_mentions       4307 non-null   object
 15  place               4307 non-null   object
dtypes: bool(1), float64(3), int64(4), object(8)
memory usage: 509.1+ KB

In [6]:
df=pd.read_csv("labeled_text.csv")

In [7]:
df.head()

,Unnamed: 0,original_text,polarity,subjectivity,label
0,0,mickeys bad move govrondesantis has now signed...,-0.037500,0.533333,negative
1,1,elections have consequences bidens historic mi...,-0.066667,0.033333,negative
2,2,coincidence 18 us food processing facilities b...,-0.077778,0.177778,negative
3,3,food processing plants being destroyed a small...,-0.100000,0.450000,negative
4,4,disgusting human being what one person calls h...,-0.500000,0.550000,negative

In [11]:
df["original_text"]=df["original_text"].apply(lambda x: x.translate(str.maketrans(' ', ' ', string.punctuation)))

In [12]:
sentence_list = [tweet for tweet in df['original_text']]
word_list = [sent.split() for sent in sentence_list]

In [17]:
id2word= corpora.Dictionary(word_list)
corpus= [word_to_id.doc2bow(tweet) for tweet in word_list]

In [20]:
lda_model = gensim.models.ldamodel.LdaModel(corpus,
                                           id2word=id2word,
                                           num_topics=4, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=512,
                                           passes=5,
                                           alpha='auto',
                                           per_word_topics=True)

In [23]:
pprint(lda_model.show_topics(formatted=False))

[(0,
  [('the', 0.035991557),
   ('of', 0.02252382),
   ('in', 0.017241972),
   ('to', 0.015990924),
   ('and', 0.013058613),
   ('is', 0.012064378),
   ('a', 0.011387204),
   ('on', 0.010727912),
   ('for', 0.009760074),
   ('it', 0.007624941)]),
 (1,
  [('to', 0.028780054),
   ('the', 0.025204936),
   ('a', 0.016249701),
   ('and', 0.013413798),
   ('is', 0.011889879),
   ('of', 0.011496854),
   ('rt', 0.010649234),
   ('with', 0.009652161),
   ('you', 0.009132141),
   ('in', 0.008231325)]),
 (2,
  [('the', 0.029012071),
   ('rt', 0.014350958),
   ('in', 0.012747899),
   ('of', 0.012239239),
   ('to', 0.009564638),
   ('on', 0.009017235),
   ('a', 0.008411665),
   ('and', 0.008278625),
   ('for', 0.0059020575),
   ('has', 0.005344706)]),
 (3,
  [('to', 0.01661693),
   ('on', 0.013006824),
   ('rt', 0.011673547),
   ('for', 0.0075931777),
   ('a', 0.007283338),
   ('from', 0.0068584047),
   ('over', 0.006269344),
   ('in', 0.0051704617),
   ('more', 0.0046857554),
   ('read', 0.0046321214)])]

In [ ]:
print(Perplexity: ", lda_model.log_perplexity(corpus))